var _ = require('lodash');
var postcss = require('postcss');

// Properties
var mapProperties = {
    'animation-delay': 'animation-verzögerung',
    'animation-direction': 'animation-richtung',
    'animation-duration': 'animation-dauer',
    'animation-fill-mode': 'animation-füll-methode',
    'animation-iteration-count': 'animation-wiederholung-anzahl',
    'animation-name': 'animation-name',
    'animation-play-state': 'animation-abspiel-zustand',
    'animation-timing-function': 'animation-takt-funktion',
    'animation': 'animation',
    'background-attachment': 'hintergrund-befestigung',
    'background-clip': 'hintergrund-beschnitt',
    'background-color': 'hintergrund-farbe',
    'background-image': 'hintergrund-bild',
    'background-origin': 'hintergrund-ursprung',
    'background-position': 'hintergrund-position',
    'background-repeat': 'hintergrund-wiederholung',
    'background-size': 'hintergrund-größe',
    'background': 'hintergrund',
    'border-bottom-color': 'rahmen-unten-farbe',
    'border-bottom-left-radius': 'rahmen-unten-links-radius',
    'border-bottom-right-radius': 'rahmen-unten-rechts-radius',
    'border-bottom-style': 'rahmen-unten-stil',
    'border-bottom-width': 'rahmen-unten-breite',
    'border-bottom': 'rahmen-unten',
    'border-collapse': 'rahmen-kollaps',
    'border-color': 'rahmen-farbe',
    'border-image': 'rahmen-bild',
    'border-image-outset': 'rahmen-bild-anfang',
    'border-image-repeat': 'rahmen-bild-wiederholung',
    'border-image-slice': 'rahmen-bild-schnitt',
    'border-image-source': 'rahmen-bild-quelle',
    'border-image-width': 'rahmen-bild-breite',
    'border-left-color': 'rahmen-links-farbe',
    'border-left-style': 'rahmen-links-stil',
    'border-left-width': 'rahmen-links-breite',
    'border-left': 'rahmen-links',
    'border-radius': 'rahmen-radius',
    'border-right-color': 'rahmen-rechts-farbe',
    'border-right-style': 'rahmen-rechts-stil',
    'border-right-width': 'rahmen-rechts-breite',
    'border-right': 'rahmen-rechts',
    'border-spacing': 'rahmen-abstand',
    'border-style': 'rahmen-stil',
    'border-top-color': 'rahmen-oben-farbe',
    'border-top-left-radius': 'rahmen-oben-links-radius',
    'border-top-right-radius': 'rahmen-oben-rechts-radius',
    'border-top-style': 'rahmen-oben-stil',
    'border-top-width': 'rahmen-oben-breite',
    'border-top': 'rahmen-oben',
    'border-width': 'rahmen-breite',
    'border': 'rahmen',
    'bottom': 'unten',
    'box-shadow': 'kasten-schatten',
    'box-sizing': 'kasten-bemessung',
    'caption-side': 'beschriftung-seite',
    'clear': 'klären',
    'clip': 'beschnitt',
    'color': 'farbe',
    'columns': 'spalten',
    'column-count': 'spalte-anzahl',
    'column-fill': 'spalte-füllung',
    'column-gap': 'spalte-lücke',
    'column-rule': 'spalte-linie',
    'column-rule-color': 'spalte-linie-farbe',
    'column-rule-style': 'spalte-linie-stil',
    'column-rule-width': 'spalte-linie-breite',
    'column-span': 'spalte-spanne',
    'column-width': 'spalte-breite',
    'content': 'inhalt',
    'counter-increment': 'zähler-erhöhen',
    'counter-reset': 'zähler-zurücksetzen',
    'cursor': 'zeiger',
    'display': 'anzeige',
    'empty-cells': 'leere-zellen',
    'filter': 'filter',
    'flex-basis': 'flex-grundlage',
    'flex-direction': 'flex-richtung',
    'flex-flow': 'flex-fluss',
    'flex-grow': 'flex-wachsem',
    'flex-shrink': 'flex-schrumpfen',
    'flex-wrap': 'flex-umbruch',
    'flex': 'flex',
    'float': 'umlaufen',
    'font-family': 'schrift-familie',
    'font-feature-settings': 'schrift-eigenschaft-einstellungen',
    'font-size': 'schrift-größe',
    'font-size-adjust': 'schrift-größe-einstellen',
    'font-style': 'schrift-stil',
    'font-variant': 'schrift-variante',
    'font-weight': 'schrift-gewicht',
    'font': 'schrift',
    'height': 'höhe',
    'hyphens': 'trennstriche',
    'justify-content': 'inhalt-ausrichten',
    'left': 'links',
    'letter-spacing': 'zeichen-abstand',
    'line-break': 'zeilen-umbruch',
    'line-height': 'zeilen-höhe',
    'list-style-image': 'listen-stil-bild',
    'list-style-position': 'listen-stil-position',
    'list-style-type': 'listen-stil-typ',
    'list-style': 'listen-stil',
    'margin-bottom': 'außenabstand-unten',
    'margin-left': 'außenabstand-links',
    'margin-right': 'außenabstand-rechts',
    'margin-top': 'außenabstand-oben',
    'margin': 'außenabstand',
    'max-height': 'max-höhe',
    'max-width': 'max-breite',
    'min-height': 'min-höhe',
    'min-width': 'min-breite',
    'opacity': 'deckkraft',
    'order': 'reihenfolge',
    'orphans': 'schusterjungen',
    'outline-color': 'kontur-farbe',
    'outline-offset': 'kontur-abstand',
    'outline-style': 'kontur-stil',
    'outline-width': 'kontur-breite',
    'outline': 'kontur',
    'overflow-x': 'überlauf-x',
    'overflow-y': 'überlauf-y',
    'overflow': 'überlauf',
    'padding-bottom': 'innenabstand-unten',
    'padding-left': 'innenabstand-left',
    'padding-right': 'innenabstand-rechts',
    'padding-top': 'innenabstand-oben',
    'padding': 'innenabstand',
    'perspective-origin': 'perspektive-ursprung',
    'perspective': 'perspektive',
    'pointer-events': 'zeiger-ereignisse',
    'position': 'position',
    'quotes': 'anführungszeichen',
    'resize': 'größenänderung',
    'right': 'rechts',
    'table-layout': 'tabelle-gestaltung',
    'tab-size': 'tab-größe',
    'text-align': 'text-ausrichten',
    'text-decoration': 'text-verzierung',
    'text-indent': 'text-einrückung',
    'text-orientation': 'text-orientierung',
    'text-overflow': 'text-überlauf',
    'text-rendering': 'text-wiedergabe',
    'text-shadow': 'text-schatten',
    'text-transform': 'text-umformung',
    'top': 'oben',
    'transition-delay': 'übergang-verzögerung',
    'transition-duration': 'übergang-dauer',
    'transition-property': 'übergang-eigenschaft',
    'transition-timing-function': 'übergang-takt-funktion',
    'transition': 'übergang',
    'unicode-bidi': 'unicode-bidi',
    'vertical-align': 'vertikale-ausrichtung',
    'visibility': 'sichtbarkeit',
    'white-space': 'weißraum',
    'widows': 'hurenkinder',
    'width': 'breite',
    'word-break': 'wort-umbruch',
    'word-spacing': 'wort-abstand',
    'word-wrap': 'wort-umschlag',
    'writing-mode': 'schreib-richtung',
    'z-index': 'ebene'
};

// Values
var mapValues = {
    'absolute': 'absolut',
    'auto': 'automatisch',
    'bold': 'fett',
    'fixed': 'fixiert',
    'hidden': 'versteckt',
    'inherit': 'erben',
    'initial': 'initial',
    'italic': 'kursiv',
    'left': 'links',
    'no-repeat': 'nicht-wiederholen',
    'none': 'keines',
    'relative': 'relativ',
    'repeat-x': 'wiederholen-x',
    'repeat-y': 'wiederholen-y',
    'repeat': 'wiederholen',
    'right': 'rechts',
    'solid': 'durchgezogen',
    'static': 'statisch',
    'unset': 'aufheben',
    // Colors
    'aliceblue': 'eisfarben',
    'antiquewhite': 'antikweiß',
    'aqua': 'wasser',
    'aquamarine': 'aquamarinblau',
    'beige': 'beige',
    'bisque': 'biskuit',
    'blanchedalmond': 'mandelweiß',
    'blueviolet': 'blauviolett',
    'burlywood': 'gelbbraun',
    'cadetblue': 'kadettenblau',
    'chocolate': 'schokolade',
    'cornflowerblue': 'kornblumenblau',
    'cornsilk': 'mais',
    'crimson': 'karmesinrot',
    'darkblue': 'dunkelblau',
    'darkcyan': 'dunkeltürkis',
    'darkgoldenrod': 'dunklegoldrunenfarbe',
    'darkgreen': 'dunkelgrün',
    'darkgray': 'dunkelgrau',
    'darkkhaki': 'dunkelkhaki',
    'darkmagenta': 'dunkelmagenta',
    'darkolivegreen': 'dunkelolivgrün',
    'darkorange': 'dunkelorange',
    'darkorchid': 'dunkleorchidee',
    'darkred': 'dunkelrot',
    'darksalmon': 'dunklelachsfarbe',
    'darkseagreen': 'dunklesseegrün',
    'darkslateblue': 'dunklesschieferblau',
    'darkviolet': 'dunkelviolett',
    'deeppink': 'tiefrosa',
    'deepskyblue': 'tiefhimmelblau',
    'dimgrey': 'gedimmtesgrau',
    'dodgerblue': 'persinningblau',
    'firebrick': 'backstein',
    'floralwhite': 'blütenweiß',
    'forestgreen': 'waldgrün',
    'ghostwhite': 'geisterweiß',
    'greenyellow': 'grüngelb',
    'honeydew': 'honigmelone',
    'hotpink': 'leuchtendrosa',
    'indianred': 'indischrot',
    'ivory': 'elfenbein',
    'khaki': 'staubfarbend',
    'lavenderblush': 'lavendelrosa',
    'lawngreen': 'grasgrün',
    'lemonchiffon': 'chiffongelb',
    'lightblue': 'hellblau',
    'lightcoral': 'helleskorallenrot',
    'lightcyan': 'helltürkis',
    'lightgray': 'hellgrau',
    'lightgreen': 'hellgrün',
    'lightpink': 'hellrosa',
    'lightsalmon': 'hellelachsfarbe',
    'lightseagreen': 'hellesseegrün',
    'lightskyblue': 'helleshimmelblau',
    'lightslategray': 'hellesschiefergrau',
    'lightsteelblue': 'hellesstahlblau',
    'lightyellow': 'hellgelb',
    'limegreen': 'limonengrün',
    'linen': 'leinen',
    'maroon': 'kastanie',
    'midnightblue': 'mitternachtsblau',
    'mintcream': 'cremigeminze',
    'mistyrose': 'altrosa',
    'moccasin': 'mokassin',
    'navajowhite': 'navajoweiß',
    'navy': 'marineblau',
    'oldlace': 'altespitze',
    'olivedrab': 'olivgrünbraun',
    'orangered': 'orangerot',
    'orchid': 'orchidee',
    'palegoldenrod': 'blassegoldrunenfarbe',
    'palegreen': 'blassgrün',
    'paleturquoise': 'blasstürkis',
    'papayawhip': 'papayacreme',
    'peachpuff': 'pfirsich',
    'plum': 'pflaume',
    'powderblue': 'taubenblau',
    'purple': 'violett',
    'rosybrown': 'rosigesbraun',
    'royalblue': 'royalblau',
    'saddlebrown': 'sattelbraun',
    'salmon': 'lachsfarben',
    'sandybrown': 'sandbraun',
    'seagreen': 'seegrün',
    'seashell': 'muschel',
    'sienna': 'siennaerde',
    'silver': 'silber',
    'slateblue': 'schieferblau',
    'slategray': 'schiefergrau',
    'snow': 'schneeweiß',
    'springgreen': 'frühlingsgrün',
    'steelblue': 'stahlblau',
    'tan': 'hautfarben',
    'teal': 'krickentengrün',
    'thistle': 'distel',
    'tomato': 'tomate',
    'turquoise': 'türkis',
    'violet': 'veilchen',
    'wheat': 'weizen',
    'whitesmoke': 'rauchfarben',
    'yellowgreen': 'gelbgrün',
    'azure': 'himmelblau',
    'black': 'schwarz',
    'blue': 'blau',
    'coral': 'koralle',
    'cyan': 'cyan',
    'gray': 'grau',
    'green': 'grün',
    'pink': 'rosa',
    'lavender': 'lavendel',
    'lime': 'limone',
    'orange': 'orange',
    'red': 'rot',
    'white': 'weiß',
    'yellow': 'gelb'
};

module.exports = postcss.plugin('postcss-german-stylesheets', function (opts) {
    opts = opts || {};

    return function (css) {
        css.walkDecls(function transformDecl(decl) {
            // Properties
            _.forEach(mapProperties, function (value, key) {
                if (decl.prop === value) {
                    decl.prop = key;
                }
            });

            // Values
            _.forEach(mapValues, function (value, key) {
                decl.value = decl.value.replace(value, key);
            });

            // Important
            if (decl.value.indexOf('!wichtig') >= 0) {
                decl.value = decl.value.replace(/\s*!wichtig\s*/, '');
                decl.important = true;
            }
        });
    };
});

// Export Properties and Values for testing
module.exports.mapProperties = mapProperties;
module.exports.mapValues = mapValues;
